# Generated by Django 5.0.2 on 2024-03-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(default='enjoy your reading', max_length=100),
        ),
    ]
