# Generated by Django 5.0.2 on 2024-03-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_article_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.CharField(default='Click on continue reading to read all', max_length=100),
        ),
    ]
