# Generated by Django 5.0.2 on 2024-03-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_article_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_title',
            field=models.CharField(default='enjoy your reading', max_length=2000),
        ),
    ]
