# Generated by Django 5.0.2 on 2024-03-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_article_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_title',
            field=models.TimeField(default='enjoy your reading'),
        ),
    ]
