# Generated by Django 5.0.2 on 2024-03-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_article_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.TextField(default='Click on continue reading to read all'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_title',
            field=models.CharField(default='enjoy your reading', max_length=2000),
        ),
    ]
