# Generated by Django 5.0.2 on 2024-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_article_preview_alter_article_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='profile_pics/profile-picture.jpg', upload_to='article_images/'),
        ),
    ]
