# Generated by Django 5.0.2 on 2024-04-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='contents',
        ),
    ]
