# Generated by Django 5.0.2 on 2024-04-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_like_unique_together_like_article_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='article_like',
            new_name='post',
        ),
    ]
