# Generated by Django 5.0.2 on 2024-04-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_rename_article_like_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
