# Generated by Django 5.0.2 on 2024-04-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_like_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
