# Generated by Django 5.0.2 on 2024-03-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_info',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
