# Generated by Django 5.0.2 on 2024-03-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_info',
        ),
    ]
