# Generated by Django 5.0.2 on 2024-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-picture.jpg', upload_to='profile_pics/'),
        ),
    ]
