# Generated by Django 5.0.2 on 2024-03-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_info',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
