# Generated by Django 5.0.2 on 2024-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_info',
            field=models.CharField(blank=True, default='hy there, im new here!!', max_length=100),
        ),
    ]
