# Generated by Django 5.0.2 on 2024-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_info',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
